# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Logic App

on:
  workflow_dispatch:
  # Trigger the workflow every time the Bicep EIS Deployment workflow ran to completion
  workflow_run:
    workflows: ["Bicep EIS Deployment"]
    branches: [main]
    types:
      - completed

  # Triggers when one of the specified files have been changed
  push:
    branches: [main]
    paths:
      - "logicAppWorkflow/**"
      - ".github/workflows/logicApp.yml"

jobs:
  logic_app_build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Package logic app workflow
        # note that zip should be installed on the agent
        run: (cd logicAppWorkflow; mkdir -p ../output; zip -r ../output/logicAppWorkflow.zip .)
      - name: Upload app zip package
        uses: actions/upload-artifact@v2
        with:
          name: logicAppWorkflow
          path: ./output/
          retention-days: 1

  logic_app_deploy:
    name: Deploy
    runs-on: self-hosted
    needs: [logic_app_build]
    environment:
      name: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_DEV}}
          # enable-AzPSSession: true
      - uses: actions/download-artifact@master
        with:
          name: logicAppWorkflow
          path: ./output/

      # Replaced with adding the profile as a SECRET - AZURE_LOGICAPP_PUBLISH_PROFILE
      # Per https://github.com/marketplace/actions/azure-functions-action#using-publish-profile-as-deployment-credential-recommended
      # This also avoids the need to install powershell on the linux self hosted runner
      #
      # - name: Get publish Profile
      #   id: publishprofile
      #   uses: azure/powershell@v1
      #   with:
      #     inlineScript: |
      #       $profile = Get-AzWebAppPublishingProfile `
      #           -ResourceGroupName ${{ secrets.AZURE_RESOURCE_GROUP }} `
      #           -Name ${{ secrets.LOGIC_APP_NAME }}
      #       $profile = $profile.Replace("`r", "").Replace("`n", "")
      #       Write-Output "::set-output name=profile::$profile"
      #     azPSVersion: latest

      - name: Deploy to Azure Logic App
        uses: Azure/functions-action@v1.3.1
        id: la
        with:
          app-name: ${{secrets.AZURE_RESOURCE_GROUP_DEV}}
          package: ./output/logicAppWorkflow.zip
          # publish-profile: ${{steps.publishprofile.outputs.profile}}
          publish-profile: ${{ secrets.AZURE_LOGICAPP_PUBLISH_PROFILE_DEV }}
