# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Logic App

env:
  LA_NAME: 'logic-eis-dev-auea'
  APIM_NAME: 'apim-eis-dev-aue'
  WORKFLOW_NAME: 'eisHttpRequest'
on:
  workflow_dispatch:
  # Trigger the workflow every time the Bicep EIS Deployment workflow ran to completion
  workflow_run:
    workflows: ["Bicep EIS Deployment"]
    branches: [main]
    types:
      - completed

  # Triggers when one of the specified files have been changed
  push:
    branches: [main]
    paths:
      - "logicAppWorkflow/**"
      - ".github/workflows/logicApp.yml"

jobs:
  logic_app_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Package logic app workflow
        run: (cd logicAppWorkflow; mkdir -p ../output; zip -r ../output/logicAppWorkflow.zip .)
      - name: Upload app zip package
        uses: actions/upload-artifact@v2
        with:
          name: logicAppWorkflow
          path: ./output/
          retention-days: 1

  logic_app_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [logic_app_build]
    environment:
      name: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_DEV}}
          enable-AzPSSession: true
      - uses: actions/download-artifact@master
        with:
          name: logicAppWorkflow
          path: ./output/

      - name: Get publish Profile
        id: publishprofile
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $profile = Get-AzWebAppPublishingProfile `
                -ResourceGroupName ${{ secrets.AZURE_RESOURCE_GROUP_DEV }} `
                -Name ${{ secrets.LOGIC_APP_NAME_DEV }}
            $profile = $profile.Replace("`r", "").Replace("`n", "")
            Write-Output "::set-output name=profile::$profile"
          azPSVersion: latest

      - name: Deploy to Azure Logic App
        uses: Azure/functions-action@v1.3.1
        id: la
        with:
          app-name: ${{secrets.AZURE_RESOURCE_GROUP_DEV}}
          package: "./output/logicAppWorkflow.zip"
          publish-profile: ${{steps.publishprofile.outputs.profile}}

  logic_app_apim_integration:
    name: Logic app APIM Update
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            $azureRestApiBasePath = "https://management.azure.com/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}/resourceGroups/${{ secrets.AZURE_RESOURCE_GROUP_DEV }}/providers"
            $worklowCallback = $(az rest --method post --uri "$azureRestApiBasePath/Microsoft.Web/sites/${{ env.LA_NAME }}/hostruntime/runtime/webhooks/workflow/api/management/workflows/${{ env.WORKFLOW_NAME }}/triggers/manual/listCallbackUrl?api-version=2018-11-01")
            $workflowResponse = $worklowCallback | ConvertFrom-Json
            $workflowBasePath= $workflowResponse.basePath

            $apimRestApiBasePath = "$azureRestApiBasePath/Microsoft.ApiManagement/service/${{ env.APIM_NAME }}"
            #update APIM backend runtime url for logic app
            $backendPath = $workflowBasePath.Substring(0,$workflowBasePath.IndexOf("/manual/"))
            $backendBody = '{\"properties\":{\"url\":\"' + $backendPath + '\"}}'
            az rest --method patch --uri "$apimRestApiBasePath/backends/${{ env.LA_NAME }}-backend?api-version=2020-06-01-preview" --body $backendBody

            #Update APIM name value for logic app rewrite url signature
            $nameValueBody = '{\"properties\":{\"value\":\"' + $workflowResponse.queries.sig + '\"}}'
            az rest --method patch --uri "$apimRestApiBasePath/namedValues/${{ env.LA_NAME }}-name-value?api-version=2020-06-01-preview --body $nameValueBody

