on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "templates/**"
      - ".github/workflows/main.yml"

name: Bicep EIS Deployment

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP_DEV }}
          template: ./templates/main.bicep
          parameters: ./templates/main.parameters-dev.json
          failOnStdErr: true
