on:
  workflow_dispatch:
  push:
    # Trigger only when any file change is detected within the path attribute.
    branches: [feature/apim-template-integration]
    paths:
      - "templates/**"
      - ".github/workflows/main.yml"

name: Bicep EIS Deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main
        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./templates/main.bicep
          parameters: ./templates/main.parameters-dev.json
          failOnStdErr: true
